theme: jekyll-theme-minimal
title: "HTF19 @ Parity"
description: Join us for a month of hacking on awesome tech for the next generation of the internet.
logo: assets/pretty_logo.png
show_downloads: false

collections:
  hackers:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "hackers"
    values:
      layout: "hacker"
