theme: jekyll-theme-minimal
title: Hacktoberfest2019 @ Parity
description: Join us for a month of hacking on awesome tech for the next generation of the internet.
logo: pretty_logo.png
show_downloads: false
